<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <title>INCRED INVOICES</title>
            <style type="text/css">
                body{margin:0;}
            </style>
    </head>
    <body>
        <center>    
            <table width="100%" bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" style="margin-left:auto; margin-right:auto; margin-top:0;margin-bottom:0;max-width:600px;">
                <tr>
                    <td bgcolor="#d01d15">
                        <table width="100%" cellspacing="0" cellpadding="0">
                            <tr>
                                <td style="font-size:0;padding-left:10px;padding-top:30px;padding-bottom:30px">
                                    <a href="//incred.pro" target="_blank"><img src="<?php echo TEMPLATE_IMG_PATH.'logo_incred.png';?>"  alt="INCRED INVOICES" border="0" style="display: block; margin:0 auto;" ></a></td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td style="padding:15px">
                        <table border="0" cellpadding="0" cellspacing="0" width="100%">
                            <?php echo $this->content; ?> 
                        </table></td>
                </tr>
                <tr>
                    <td bgcolor="#ececed" style="padding-left:10px;padding-bottom:21px;padding-top:15px;padding-bottom:15px;text-align:left">
                        <p style="margin:0;padding:0; font-family:Arial, Helvetica, sans-serif;color:#666666; font-size:12px; line-height:18px">Copyright 2018. incredinvoices. All rights reserved.<br/>
                            <a style="color:#ff8208; text-decoration:none; font-weight:bold;" href="//incred.pro/terms-of-service" target="_blank">Terms</a> | <a style="color:#ff8208; 
                                                                                                                                                                  text-decoration:none; font-weight:bold;" href="//incred.pro/privacy-policy" target="_blank">Privacy Policy</a></p>
                    </td>
                </tr>
                <tr>
                    <td bgcolor="#45484a" style="font-size:11px;font-family:Arial, Helvetica, sans-serif;color:#FFFFFF;padding-left:10px;padding-right:10px;padding-top:15px;padding-bottom:15px;text-align:left">To make sure our email updates are delivered to your inbox, please add <a style="color:#ff8208; text-decoration:none;" href="mailto:wecare@incred.pro"><strong>WeCare@incred.pro</strong></a> to your email Address Book.</td>
                </tr>
            </table>
        </center>
    </body>    
</html>